#!/bin/bash
# Helper script to guide you through adding the GitHub Secret to .env

echo "═══════════════════════════════════════════════════════"
echo "  📝 How to Get Your API Key from GitHub Secrets"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "1. Open this URL in your browser:"
echo "   👉 https://github.com/asamaka/engzny/settings/secrets/actions"
echo ""
echo "2. Find 'CLAUDE_API_KEY' in the list"
echo ""
echo "3. Click on it (you can't view the value, but you stored it there)"
echo ""
echo "4. OPTION A: Share the key value with Claude Code"
echo "   Just paste it in the chat and Claude will add it to .env"
echo ""
echo "5. OPTION B: Add it manually:"
echo "   Edit: $PWD/.env"
echo "   Add line: ANTHROPIC_API_KEY=sk-ant-your-key-here"
echo ""
echo "6. Then run: node scripts/validate-api-keys.js"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "💡 TIP: GitHub Secrets are encrypted. You need to copy"
echo "the original key value you saved when you created it."
echo ""
echo "Don't have the original key? Get a new one:"
echo "👉 https://console.anthropic.com/"
echo ""
